[package]
name = "datapond-macro"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
datapond = { path = ".." }
proc-macro-hack = "0.5"
